### ISSUE TITLE
显示“读取Tag失败，请尝试日文和英文“

### ISSUE THREAD

**Issue by QSlotus** [cssxsh/pixiv-helper#103]
如题，但是我换成日文和英文也不行
![$IE{_HQF_5 I{)9Y`XQJB}I](https://user-images.githubusercontent.com/109905194/228550426-bdd3a5a1-7333-47b5-8b0b-84783837bc9a.png)

**Comment by cssxsh** [comment]
你需要先缓存
然后使用 tag
（因为 pixiv 你不充会员搜出来的图并不好，只能先缓存，然后挑好的图）
