### ISSUE TITLE
发送的图片中含有大量风景图是为什么？以及删除指令如何使用？能否快速删除所有图片记录？

### ISSUE THREAD

**Issue by Tracheliumlhy** [cssxsh/pixiv-helper#104]
还有r18限制的问题，r18图片是否能够缓存？能否解除r18图片的发送限制？
以及会出现发送的图片失效不显示，转发的16张图片消息记录无法进入等问题

**Comment by cssxsh** [comment]
因为它本质上只是一个简单的 pixiv 爬虫，能爬到什么却决于 pixiv 给你的推送
