### ISSUE TITLE
W/console: 无法解析 <uid> 为长整数

### ISSUE THREAD

**Issue by Kirito17881154079** [cssxsh/pixiv-helper#105]
![QQ图片20230703180251](https://github.com/cssxsh/pixiv-helper/assets/138461820/f91ca540-70a1-42d3-aa5f-e57d36be3f9a)
请问出现这种情况是为什么，该如何解决

**Comment by cssxsh** [comment]
有没有可能，`<uid>` 是要换成 你自己的 uid 95909371

**Comment by Kirito17881154079** [comment]
解决了，谢谢喵
（第一次接触这方面的东西，私密马赛
