### ISSUE TITLE
缓存任务终止后无法再开启

### ISSUE THREAD

**Issue by Oeeder** [cssxsh/pixiv-helper#17]
在下载最新的版本只会。
使用Tag缓存，机器人能正常回复：已建立缓存任务
但好几天发现下来根本没有缓存到一张图片

这边后台在建立任务时有以下提示：
![QQ截图20210708155532](https://user-images.githubusercontent.com/75010467/124885338-bfaa4f00-e005-11eb-8119-7278333fe13c.jpg)
请问该如何解决？

**Comment by cssxsh** [comment]
是否曾经使用指令终止了缓存？

**Comment by Oeeder** [comment]
有的，有多次试过停止缓存后再建立缓存任务，还是这样

**Comment by cssxsh** [comment]
> 有的，有多次试过停止缓存后再建立缓存任务，还是这样

可能是停止指令有bug，导致无法再次缓存

**Comment by cssxsh** [comment]
https://github.com/cssxsh/pixiv-helper/releases/tag/v0.7.4

**Comment by cssxsh** [comment]
> https://github.com/cssxsh/pixiv-helper/releases/tag/v0.7.4

这个版本有解决问题吗？

**Comment by Oeeder** [comment]
目前情况比较奇怪。
确实是有正常的建立TAG缓存任务了。
我这边后台查看建立TAG任务时没有任何的报错。
但经过我这一个晚上和今天一个白天的测试。
无论我是用指定tag缓存，还是使用/<cache> <recommended>进行缓存。
机器人都不会有缓存的动作进行。

我这边是在登录pixiv账户成功的前提下简历缓存的任务的，但机器人过了一晚上时间，并没有开始任何一个图片的缓存。
本来我以为是API限制的问题，但我发现后台也没0.7.2-M2版本中提示的API被限制，延迟:XXXXXms的提示。
所以我觉得会不会是建立了缓存任务但是没有进行？

**Comment by cssxsh** [comment]
> 目前情况比较奇怪。
> 确实是有正常的建立TAG缓存任务了。
> 我这边后台查看建立TAG任务时没有任何的报错。
> 但经过我这一个晚上和今天一个白天的测试。
> 无论我是用指定tag缓存，还是使用/ 进行缓存。
> 机器人都不会有缓存的动作进行。
> 
> 我这边是在登录pixiv账户成功的前提下简历缓存的任务的，但机器人过了一晚上时间，并没有开始任何一个图片的缓存。
> 本来我以为是API限制的问题，但我发现后台也没0.7.2-M2版本中提示的API被限制，延迟:XXXXXms的提示。
> 所以我觉得会不会是建立了缓存任务但是没有进行？

tag 缓存是会 按照色图标准过滤不符合要求的图片的，如果你的tag太冷门很可能拿不到，推荐先用  `/cache recommended` 缓存

**Comment by cssxsh** [comment]
如果你想看到更详细的日志 需要修改 mirai-console 的 日志配置，在文件夹 config/Console 下

**Comment by cssxsh** [comment]
我的锅 涩图标准 里有个内容类型，我貌似写错判断了，草

**Comment by cssxsh** [comment]
https://github.com/cssxsh/pixiv-helper/releases/tag/v0.7.5
