### ISSUE TITLE
认证百度账号时出错

### ISSUE THREAD

**Issue by Eudiplozoon** [cssxsh/pixiv-helper#3]
已经在百度申请了api，在绑定页面复制验证码发出之后报错 百度云用户认证失败, invalid code , expired or revoked

**Comment by Eudiplozoon** [comment]
![QQ20210702-005910](https://user-images.githubusercontent.com/37258131/124162195-d5cd8200-dad0-11eb-9d40-9f9e78064190.png)
![QQ20210701-210841](https://user-images.githubusercontent.com/37258131/124162334-eed63300-dad0-11eb-8a52-a8dfb1e38703.png)

同时会不断出现这样的报错，求解。。。

**Comment by cssxsh** [comment]
> ![QQ20210702-005910](https://user-images.githubusercontent.com/37258131/124162195-d5cd8200-dad0-11eb-9d40-9f9e78064190.png)
> ![QQ20210701-210841](https://user-images.githubusercontent.com/37258131/124162334-eed63300-dad0-11eb-8a52-a8dfb1e38703.png)
> 
> 同时会不断出现这样的报错，求解。。。

编译的时候忘记更新上游依赖了，出了一点问题
