### ISSUE TITLE
pixiv login error

### ISSUE THREAD

**Issue by FZSF-623** [cssxsh/pixiv-helper#4]
When I use pixiv login ,my robot show this  
![image](https://user-images.githubusercontent.com/73884671/124223515-7013e100-db36-11eb-9c73-600e300986d3.png)

**Comment by cssxsh** [comment]
with upbit/pixivpy#158

**Comment by cssxsh** [comment]
`/pixiv login` command removed, `/pixiv sina` As a substitute
