### ISSUE TITLE
saucenao搜图没有反应，是我的配置有误吗？

### ISSUE THREAD

**Issue by q1w231** [cssxsh/pixiv-helper#49]
<img src="http://shp.qpic.cn/collector/1844744518/ff2348d9-3e9b-4395-870a-ea76315e6734/0">

**Comment by cssxsh** [comment]
有搜图的权限吗

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai-console/blob/master/docs/BuiltInCommands.md#授予所有用户执行某个指令的权限

**Comment by q1w231** [comment]
有的

**Comment by cssxsh** [comment]
你具体是 怎么个搜法

**Comment by q1w231** [comment]
我：/搜图
机器人：300s内，请发送图片

然后我发送图片机器人没反应

**Comment by cssxsh** [comment]
> 我：/搜图
> 机器人：300s内，请发送图片
> 
> 然后我发送图片机器人没反应

日志应该会有
`搜索 http://gchat.qpic.cn/gchatpic_new/...`
如果没有这个，有可能是没有接收到图片
