### ISSUE TITLE
服务器下载问题

### ISSUE THREAD

**Issue by Shuyuxu211** [cssxsh/pixiv-helper#50]
出现
1、Pixiv Download 错误, 已忽略: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
2、下载超时问题

我在本机上使用bot时网络是正常的，但是在阿里云上则出现以上问题，服务器是1m的，下载正常文件网速还可以但是下这个插件则非常慢几乎没有网速，我猜测可能是阿里云做了某些墙的限制，请问有办法解决嘛？
我已经查阅过论坛评论，修改过超时设置至60s，尝试过镜像以及反向代理，甚至自己手动挂了个ssr，但是下载速度还是过慢，下午给的指令凌晨bot才会回复。

**Comment by Shuyuxu211** [comment]
环境是阿里云的轻量应用服务器，2核2g，Windows2019

**Comment by cssxsh** [comment]
1. 不建议挂在服务器上
2. 网络太差了，而且 1M小水管 能顶多少用你自己不清楚吗
3. 代理治标不治本，

[1.4.3](https://github.com/cssxsh/pixiv-helper/releases/tag/v1.4.3) 代理也会对下载生效，一旦配置代理，多线程下载器会对代理会造成很大的负荷，其中利害自己权衡

**Comment by Shuyuxu211** [comment]
我尝试一下新版代理吧，感谢回复
