### ISSUE TITLE
cookie登录没有响应

### ISSUE THREAD

**Issue by clonek** [cssxsh/pixiv-helper#51]
![image](https://user-images.githubusercontent.com/38306804/130434836-a3ede398-d8c4-4b24-8629-67dd4a28ae7b.png)
![image](https://user-images.githubusercontent.com/38306804/130435242-1c552bc5-bd99-4a28-99c8-1198aeee5118.png)

聊天环境输入任何指令都没有响应

**Comment by cssxsh** [comment]
<https://github.com/mamoe/mirai-console/blob/master/docs/BuiltInCommands.md#授予一个用户执行所有指令的权限>
