### ISSUE TITLE
用微博和cookie登录时显示pixiv API错误

### ISSUE THREAD

**Issue by clonek** [cssxsh/pixiv-helper#52]
![image](https://user-images.githubusercontent.com/38306804/130463106-901b13ba-e22e-4f3c-a6c3-c35b43b33501.png)
如图，是我哪里设置错了吗

**Comment by cssxsh** [comment]
你是不是开了代理

**Comment by clonek** [comment]
我开了一个host本地代理工具
 今天我重新部署了一下机器人 然后用cookie可以登录了 不知道是哪里问题
不好意思打扰大佬了
