### ISSUE TITLE
通过 转发消息 回复 搜索结果

### ISSUE THREAD

**Issue by FridayAnubis** [cssxsh/pixiv-helper#59]
**Bug:** 在使用ascii2d搜图时，检索结果中相似度会显示为NaN%；
**建议:** 1、搜图结果往往需要手动验证，如果能加入搜索结果的缩略图就太好了；
2、我发现其他群友有一种搜图机器人，它可以把搜图结果合并成一个转发消息集再发到群里，目前的机器人因为搜图时发送大量文字和链接经常被风控；
3、如果使用了2中的搜图方式，那么是否可以把ascii2d搜图和saucenao搜图整合进一个指令一起搜索）

**Comment by cssxsh** [comment]
这不是bug，ascii2d搜索结果本来就没有相似度

1. 搜图结果有时候会出奇怪的图，或者r18

**Comment by cssxsh** [comment]
处理成 转发消息 并不困难，但是风控机制是黑箱，
没有任何证据表明能有效处理风控。

作为防止刷屏的处理倒是有一定价值

**Comment by cssxsh** [comment]
另外，请不要将几个问题塞进一个issue里，
一个 issue 里应该只明确一个需要解决的问题

**Comment by cssxsh** [comment]
就测试结果来看，转发更容易被风控

**Comment by cssxsh** [comment]
with 1.6.2
