### ISSUE TITLE
百度云账号认证链接缺少client_id

### ISSUE THREAD

**Issue by Orisland** [cssxsh/pixiv-helper#6]
不行哎，认证的时候出现问题，
/backup auth后出现的链接打开就是下面的错误，NETDISKOAUTHCONFIG.YML已经填了，应用也创建了。

您遇到了错误！
错误代码：invalid_request
错误信息：The request is missing a required parameter
详细描述：缺少必要参数，请开发者参照 Web应用换取Access Token或JS应用换取Access Token说明文档中指明的必传参数。

**Comment by Orisland** [comment]
少了一个变量吧emm
client_id？
https://openapi.baidu.com/oauth/2.0/authorize?client_id=&response_type=code&redirect_uri=oob&scope=basic%2Cnetdisk&display=
我自己填上之后
<img width="492" alt="image" src="https://user-images.githubusercontent.com/59354152/124250293-533bd580-db57-11eb-8285-0c208d022fe9.png">

**Comment by cssxsh** [comment]
不是，后台代码有点问题，等更新把

**Comment by cssxsh** [comment]
而且 issue 重复了

**Comment by Orisland** [comment]
> 而且 issue 重复了

哎，我主要是觉得这两个严重出错的方式不太一样，就开了两个……
