### ISSUE TITLE
过滤不成功

### ISSUE THREAD

**Issue by Haocen2004** [cssxsh/pixiv-helper#60]
PID: 86329545
配置文件里面过滤都开了
环境：私聊发送ero
过滤了 但没完全过滤（
已确认为最新release版本

**Comment by Haocen2004** [comment]
补：图片看起来问题不大 但是图片tag（

**Comment by cssxsh** [comment]
? 这个并没有标记为 R18 并不在过滤范围内

**Comment by Haocen2004** [comment]
![IMG_20211115_233458.jpg](https://user-images.githubusercontent.com/25221696/141809530-38564249-123b-414d-8ad3-2b9ce285afbc.jpg)
abab 这个tag（
在pixez里面会被遮罩拦住（

**Comment by cssxsh** [comment]
> ![IMG_20211115_233458.jpg](https://user-images.githubusercontent.com/25221696/141809530-38564249-123b-414d-8ad3-2b9ce285afbc.jpg) abab 这个tag（ 在pixez里面会被遮罩拦住（

实际上R18并不是使用 tag标记的，而是有专门的属性
![I@}HLEO$C}22V8U8)23}GR5](https://user-images.githubusercontent.com/32539286/141809983-29c461e5-d42b-453e-b77a-1b6becd68819.png)

**Comment by Haocen2004** [comment]
了解了（
