### ISSUE TITLE
SQLITE 不支持 非主键 自增

### ISSUE THREAD

**Issue by ccl688** [cssxsh/pixiv-helper#65]
启动报错提示： Create Table by create.sqlite.sql with SQLite ，指令无反应

**Comment by cssxsh** [comment]
1. 版本
2. 日志内容

请完善这两点

**Comment by ccl688** [comment]
版本是最新的1.8.0,工作目录生成的那个sqlite文件是空的，回退到上一个版本后可以启动了。日志现在没有。指令是我的问题 没有给权限

**Comment by cssxsh** [comment]
1.8.1 尝试修复
