### ISSUE TITLE
[Feature Request] Can set the limit of caching images

### ISSUE THREAD

**Issue by madoka-chann** [cssxsh/pixiv-helper#73]
## 举例

`/<cache> <tag> [tag] [limit]?`
`/<cache> <recommended> [limit]?`
`/<task> <cache> {args} [limit]?`
`/<cache> ...`
`/<task> <cache> ...`

[limit]参数指缓存成功的图片数量。

## 一些革新

这将能够防止缓存过多同类型的图片，缓存的图片库将会很大程度上对应使用者的需求。
#### 自动化：
取缔`/cache stop` ，使用者无需拘谨于设置了缓存任务 `不知/在意` 何时停止的窘境，
同时在另一个维度上，此参数将会减少未来删除指令完善后，使用其删除自己 `不需要、过于冗余` 的图片的必要。
#### 个性化：
从此，使用者可以更有创造性的个性化基于本人实际需求的 `本地、百度云` 图片缓存库，
## 一个问题
根据收藏数过滤缓存图片是从最高的收藏数（排行榜）往下递减到设置的过滤收藏数，还是从下往上？
而从上往下无疑是对 [limit] 这个概念变量的绝佳设计。

**Comment by cssxsh** [comment]
从缓存数上 limit 很鸡肋，如果想减少缓存结果，还是自己提高配置里的 **色图标准** 比较实在

**Comment by madoka-chann** [comment]
整体上来讲确实是这样，只不过我这样想掺杂了个人经验。我先close掉了，先体验一个月再看看有什么好的想法
