### ISSUE TITLE
[Improvement] Enhancements to sending mode (Theoretically let bot be safer)

### ISSUE THREAD

**Issue by madoka-chann** [cssxsh/pixiv-helper#74]
## 单张图片发送模式：
1、默认为forward而不是normal理论上来说应该会减少封号几率，r18图片虽然过滤了还是会有很多危险的大尺度导致封号。
2、群聊forward模式，将转发消息里的对象随机为机器人所在的某个群（非触发色图的本群）群员，而不是一直都是发送指令的人。还是理论上来说，应该会让群和自己、bot都更加安全。
## 最简化图片信息：
1、可以设置只转发图片，没有任何其他相关信息。加上转发的所指对象是非本群的群员，应该可以伪装成自己是无辜的（表示全都是从其它群那里收集的！），或者自己不是机器人。

以上思路供参考，可以被证伪那就最好不过啦~

**Comment by cssxsh** [comment]
**只转发图片** 是不会考虑的，本身来说机器人自动转发图片就是未经原作者同意的行为，还隐藏掉作者信息就过分了

图片上传之后就会 开始被tx讯检测，然后无论是单条消息还是转发，
如果包含了被标记风控的图片就无法被其他人看到，也就是发不出去

**Comment by FuYon** [comment]
那转发模式的优点只有折叠消息吗

**Comment by madoka-chann** [comment]
也就是说，在发图这个维度上，是发出去然后被腾讯标记风控的大尺度图片导致封号？那根本原因就成了尺度的问题了，因为我看到
![image](https://user-images.githubusercontent.com/57851695/154836660-3771162a-6644-4a71-85db-948adefff161.png)
之后是觉得转发模式会有一定的帮助的，如果这个帮助仅仅是在折叠消息从而降低封号风险那就没事了

**Comment by madoka-chann** [comment]
应该还需要补充一点，文字和图片同时发送容易导致风控吧，所以在某些情况下分开图片信息与图片本身是不是比较，然后两条消息间设置一定的延迟。还是说这样没什么作用，比较冗余
