### ISSUE TITLE
IllustInfo.useImageResources 中 多余的 replicate 

### ISSUE THREAD

**Issue by m122469119** [cssxsh/pixiv-helper#75]
![YB E68D16H7 P@ _KR (XJ9](https://user-images.githubusercontent.com/9696919/155045971-ed09bfeb-3d74-4f80-9a1c-2c0fcffa1cf4.png)

**Comment by cssxsh** [comment]
？

**Comment by cssxsh** [comment]
忘记把测试中添加的代码处理掉了
with https://github.com/cssxsh/pixiv-helper/releases/tag/v1.9.4
