### ISSUE TITLE
任务删除失败

### ISSUE THREAD

**Issue by Haocen2004** [cssxsh/pixiv-helper#78]
![Screenshot_2022-03-31-12-51-42-041_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/25221696/160979131-b42ac639-4dbe-4fae-8c35-056ff59868d9.jpg)
rt 空格没有正确过滤 加上引号也没有用

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/pixiv-helper/releases/tag/v1.9.5

**Comment by Haocen2004** [comment]
fix confirm
这两天省检没有及时更新
