### ISSUE TITLE
对`R18禁止！`的一些建议

### ISSUE THREAD

**Issue by LaoLittle** [cssxsh/pixiv-helper#79]
有时候机器人准备发送R18图片就会把图片替换为标题文字，这样也可以防止机器人被封

但是，为什么不能发送另一张图片呢？

比如发送`涩图`，如果准备发送的是R18就换一张

**Comment by cssxsh** [comment]
我记得 `ero`, `tag` 这两个指令是有配置自动过滤r18 的

**Comment by Speechless22** [comment]
R18
GKD！
🥵
