### ISSUE TITLE
缓存图片报错：SQLITE_CONSTRAINT_NOTNULL

### ISSUE THREAD

**Issue by himesamanoyume** [cssxsh/pixiv-helper#83]
![QQ截图20220506233029](https://user-images.githubusercontent.com/59681886/167164944-cabc5ece-7ae3-4002-bfad-f1db0010051c.png)

之前用的老版本插件(1.7.32) 今天机器人和插件全部最新版本新装在别处后 缓存图片时报错

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/pixiv-helper/releases/tag/v1.9.7
