### ISSUE TITLE
延迟设定相关

### ISSUE THREAD

**Issue by Haocen2004** [cssxsh/pixiv-helper#85]
想问下/<setting> <interval> [sec]指的是哪个延迟
以及有没有bot发图全局限速（比如在一个群内有人通过ero/tag/boom获取图片 在下一次收到类似指令时中间强制间隔一段时间）

**Comment by cssxsh** [comment]
？

如果 你是指 `/setting interval [sec]` 的话，是指 task 的发送间隔

至于为什么没有全局限速，因为我认为这是 `群管理` 的工作内容

**Comment by Haocen2004** [comment]
好的
~为什么会吞commit内容~
