### ISSUE TITLE
cookie登录时报错

### ISSUE THREAD

**Issue by DSword91** [cssxsh/pixiv-helper#87]
![QQ截图20220518201252](https://user-images.githubusercontent.com/58614972/169037326-00cfea36-d2d5-4d60-ad4b-dca9b479561b.png)
使用了EditThisCookie抓取cookie并导出
但是出现了这种情况...
请问应该如何解决

**Comment by cssxsh** [comment]
可能是没能成功从cookie获取登录状态，你可以多尝试几遍

**Comment by cssxsh** [comment]
with https://github.com/cssxsh/pixiv-helper/releases/tag/v1.10.0-M2

修复一些可能的登录问题
