### ISSUE TITLE
/pixiv selenium 登录出错

### ISSUE THREAD

**Issue by Seayay** [cssxsh/pixiv-helper#95]
![Screenshot_2022-07-13-12-19-08-83_2665fb67b16260a8d818298cef8dc107.jpg](https://user-images.githubusercontent.com/92374733/178653101-46c81ce2-fb10-4597-9fb3-f4177c3ab936.jpg)

**Comment by cssxsh** [comment]
#94 
pixiv服务器的问题，你可以试试 2.0.0-M4

**Comment by Seayay** [comment]
就是2.0.0-M4

**Comment by cssxsh** [comment]
那就多试几次
登录之后刷新一下之类的
这个没法处理，pixiv服务器端的问题，也许是多了什么验证之类的

**Comment by cssxsh** [comment]
和另一个issue是一样的问题，这个就关掉了
