### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by OToNaShiAKi** [cssxsh/pixiv-helper#96]
想咨询一下目前第二代是还没有开发完成不能用么
没有在文档里找到第二代的安装指令 只看到了前置插件的安装指令

**Comment by cssxsh** [comment]
你可以直接到 https://github.com/cssxsh/pixiv-helper/releases 下载

**Comment by OToNaShiAKi** [comment]
问下get指令获取图片后怎么关掉r18禁止获取到图片啊
