### ISSUE TITLE
BUG：/search NaN%相似度

### ISSUE THREAD

**Issue by greenhandzdl** [cssxsh/pixiv-helper#99]
![Screenshot_20220729_215856_com tencent mobileqq](https://user-images.githubusercontent.com/61241103/181777044-0714a9d6-ec7c-482f-9cfc-561379b75f49.jpg)
![-39236b83ffce8e45](https://user-images.githubusercontent.com/61241103/181777049-5e7e3fb5-7093-4ccc-b70d-434244b4c29b.png)

**Comment by greenhandzdl** [comment]
还有forward对象的头像整错了吧，怎么变成$sender的了

**Comment by cssxsh** [comment]
NaN 是因为api没返回 相似度，这个是没办法的
转发消息是我故意的（好玩，在群聊里面你会发现全是群友）
